
<!DOCTYPE html>
<html>
<head>
	<title>SJTest Test</title>
<!-- Bootstrap -->
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
   
  <script src="../SJTest.js"></script>
  <script>  	
  	SJTest.on = true;
  </script>

</head>
<body>

	<h2>All these tests should fail!</h2>

	<script>
	SJTest.run({name:'Failing Tests',
		
		"waiting-fail-by-error": function(test) {	
			var s = new Date().getTime();
			var fn = function(){ var d = new Date().getTime() - s; return d > 1000;};
			assert( ! fn());		
			test.setStatus('waiting');
			SJTest.waitFor(fn)
			.done(function() {
				throw "slow fail"; // Note: This uncaught error message won't get reported, though you can find it in the console. 
				// The test will now timeout -- doing test.setStatus('fail') is therefore better. 
			});
		},
	
		"waiting-fail-self": function(test) {
			var s = new Date().getTime();
			var fn = function(){ var d = new Date().getTime() - s; return d > 1000;};
			assert( ! fn());		
			test.setStatus('waiting');
			SJTest.waitFor(fn)
			.done(function() {
				test.setStatus('fail');
				test.details = 'Oh well -- that is what this test is meant to do!';
			});
		}	
	});	
	</script>

</body>
</html>
